name: alumni_network
description: "Alumni Network Platform Mobile and Web client."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages:
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  get_it: 7.6.4
  dio: 5.3.3

  # UI packages:
  cached_network_image: 3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
